import assert from "node:assert/strict"
import test from "node:test"
import { materialize } from "../src/agents"

const SOURCE = `---
description: Test agent.
mode: primary
---

Body text.
`

test("materialize injects marker and model", () => {
  const out = materialize(SOURCE, "Kimi/kimi-k3#max")
  assert.ok(out.startsWith("---\n# generated by my-opencode-config\n"))
  assert.ok(out.includes("\nmodel: Kimi/kimi-k3#max\n---"))
  assert.ok(out.endsWith("Body text.\n"))
})

test("materialize without a mapping emits no model line", () => {
  const out = materialize(SOURCE, undefined)
  assert.ok(!out.includes("model:"))
  assert.ok(out.startsWith("---\n# generated by my-opencode-config\n"))
})

test("materialize replaces an existing model line and stale marker", () => {
  const once = materialize(SOURCE, "A/a")
  const twice = materialize(once, "B/b#v")
  assert.equal(twice.match(/model:/g)?.length, 1)
  assert.equal(twice.match(/generated by my-opencode-config/g)?.length, 1)
  assert.ok(twice.includes("model: B/b#v"))
})

test("materialize passes content without frontmatter through untouched", () => {
  assert.equal(materialize("no frontmatter here", "A/a"), "no frontmatter here")
})
