import assert from "node:assert/strict"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs"
import os from "node:os"
import path from "node:path"
import test from "node:test"
import { setupAgents } from "../src/agents"
import { globalConfigDir } from "../src/paths"

const AGENT_IDS = ["main", "codeleader", "insight", "coder", "codebuilder", "general", "scout"]

async function withXdg<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const dir = mkdtempSync(path.join(os.tmpdir(), "moc-agents-"))
  const saved = process.env.XDG_CONFIG_HOME
  process.env.XDG_CONFIG_HOME = dir
  try {
    return await fn(dir)
  } finally {
    if (saved === undefined) delete process.env.XDG_CONFIG_HOME
    else process.env.XDG_CONFIG_HOME = saved
  }
}

function mockAgentCtx() {
  const removed: string[] = []
  const title: Record<string, unknown> = {}
  let defaultAgent: string | undefined
  const ctx = {
    agent: {
      transform: async (
        fn: (editor: {
          remove: (id: string) => void
          get: (id: string) => Record<string, unknown> | undefined
          default: (id: string) => void
        }) => void,
      ) =>
        fn({
          remove: (id) => removed.push(id),
          get: (id) => (id === "title" ? title : undefined),
          default: (id) => {
            defaultAgent = id
          },
        }),
      reload: async () => {},
    },
  }
  return { ctx, removed, title, defaultAgent: () => defaultAgent }
}

test("setupAgents materializes bundled agents with the mapped model", async () => {
  await withXdg(async () => {
    const { ctx } = mockAgentCtx()
    const cleanup = await setupAgents(ctx as never)
    try {
      const dir = path.join(globalConfigDir(), "agents")
      for (const id of AGENT_IDS) {
        const file = path.join(dir, `${id}.md`)
        assert.ok(existsSync(file), `${id}.md generated`)
        const text = readFileSync(file, "utf8")
        assert.ok(text.startsWith("---\n# generated by my-opencode-config\n"), `${id} marker`)
      }
      assert.match(readFileSync(path.join(dir, "main.md"), "utf8"), /\nmodel: Kimi\/kimi-k3#max\n/)
      assert.match(readFileSync(path.join(dir, "coder.md"), "utf8"), /\nmodel: Kimi\/kimi-k3\n/)
    } finally {
      await cleanup()
    }
  })
})

test("setupAgents removes stale generated files but keeps user files", async () => {
  await withXdg(async () => {
    const dir = path.join(globalConfigDir(), "agents")
    mkdirSync(dir, { recursive: true })
    writeFileSync(path.join(dir, "ghost.md"), "---\n# generated by my-opencode-config\ndescription: stale\n---\n")
    writeFileSync(path.join(dir, "custom.md"), "---\ndescription: mine\n---\n")
    const { ctx } = mockAgentCtx()
    const cleanup = await setupAgents(ctx as never)
    try {
      assert.ok(!existsSync(path.join(dir, "ghost.md")), "stale generated file removed")
      assert.equal(readFileSync(path.join(dir, "custom.md"), "utf8"), "---\ndescription: mine\n---\n")
    } finally {
      await cleanup()
    }
  })
})

test("setupAgents transform prunes builtins and configures the title agent", async () => {
  await withXdg(async () => {
    const { ctx, removed, title, defaultAgent } = mockAgentCtx()
    const cleanup = await setupAgents(ctx as never)
    try {
      assert.deepEqual(removed.sort(), ["build", "explore", "plan"])
      assert.equal(title.steps, 1)
      assert.deepEqual(title.model, { providerID: "DeepSeek", id: "deepseek-v4-flash", variant: "max" })
      assert.equal(defaultAgent(), "main")
    } finally {
      await cleanup()
    }
  })
})

test("cleanup removes every generated file but keeps user files", async () => {
  await withXdg(async () => {
    const dir = path.join(globalConfigDir(), "agents")
    mkdirSync(dir, { recursive: true })
    writeFileSync(path.join(dir, "custom.md"), "---\ndescription: mine\n---\n")
    const { ctx } = mockAgentCtx()
    const cleanup = await setupAgents(ctx as never)
    await cleanup()
    for (const id of AGENT_IDS) assert.ok(!existsSync(path.join(dir, `${id}.md`)), `${id}.md removed`)
    assert.ok(existsSync(path.join(dir, "custom.md")), "user file survives cleanup")
  })
})
