// Agent installation and model assignment.
//
// The plugin API's agent transform editor only covers configured agents, not
// file-discovered ones, so the bundled agents/*.md are materialized into the
// global config directory (~/.config/opencode/agents/) as generated files:
// each file's frontmatter gets its `model` from the agent→model mapping
// (my-opencode-config.jsonc; ~/.config/opencode/my-opencode-config.jsonc
// overrides per-agent). Mapping changes regenerate the files and reload, so
// model changes apply without a restart.
//
// Generated files carry a "# generated by my-opencode-config" marker; only
// marked files are overwritten or removed, user files with the same names are
// left alone. Built-in agents remain visible to the transform editor, so the
// title model is applied there instead.

import { Model, Plugin, Provider } from "@opencode/plugin"
import { promises as fs } from "node:fs"
import path from "node:path"
import { loadMapping, parseModelRef, watchMapping } from "./mapping"
import { globalConfigDir, packageRoot } from "./paths"

type Context = Parameters<NonNullable<Parameters<typeof Plugin.define>[0]["setup"]>>[0]

const bundledDir = path.join(packageRoot, "agents")
const MARKER = "# generated by my-opencode-config"

// Replaces or inserts the `model` line in the YAML frontmatter and ensures the
// generated marker is present right after the opening fence.
export function materialize(content: string, modelRef: string | undefined): string {
  const open = content.indexOf("---")
  const close = content.indexOf("\n---", open + 3)
  if (open !== 0 || close === -1) return content
  let front = content.slice(3, close)
  const body = content.slice(close)

  front = front
    .split("\n")
    .filter((line) => !line.startsWith("model:") && line.trim() !== MARKER)
    .join("\n")
  const modelLine = modelRef ? `\nmodel: ${modelRef}` : ""
  return `---\n${MARKER}${front}${modelLine}${body}`
}

async function isOwned(file: string): Promise<boolean> {
  const head = await fs.readFile(file, "utf8").catch(() => "")
  return head.slice(0, 200).includes(MARKER)
}

// Deletes generated (marker-owned) files in target whose names are not in
// keep. User files are never touched.
async function removeStale(target: string, keep: ReadonlySet<string>): Promise<void> {
  for (const file of await fs.readdir(target).catch(() => [] as string[])) {
    if (keep.has(file)) continue
    const dst = path.join(target, file)
    if ((await fs.lstat(dst).catch(() => null))?.isFile() && (await isOwned(dst))) {
      await fs.unlink(dst).catch(() => {})
    }
  }
}

// Removes every generated agent file. Called when the agents module is
// disabled so previously materialized files do not linger.
export async function sweepGeneratedAgents(): Promise<void> {
  await removeStale(path.join(globalConfigDir(), "agents"), new Set())
}

export async function setupAgents(ctx: Context): Promise<() => Promise<void>> {
  const target = path.join(globalConfigDir(), "agents")
  let mapping = await loadMapping()

  const sync = async () => {
    await fs.mkdir(target, { recursive: true })
    const bundled = new Set<string>()
    for (const file of (await fs.readdir(bundledDir)).sort()) {
      if (!file.endsWith(".md")) continue
      bundled.add(file)
      const id = file.slice(0, -3)
      const dst = path.join(target, file)
      const stat = await fs.lstat(dst).catch(() => null)
      if (stat && !(await isOwned(dst))) {
        console.warn(`[my-opencode-config] skip ${dst}: a user file already exists`)
        continue
      }
      const source = await fs.readFile(path.join(bundledDir, file), "utf8")
      const next = materialize(source, mapping[id])
      const current = stat ? await fs.readFile(dst, "utf8").catch(() => "") : ""
      if (next !== current) await fs.writeFile(dst, next)
    }
    await removeStale(target, bundled)
  }
  await sync()

  await ctx.agent.transform((editor) => {
    // Unused built-ins. The custom general.md overrides the built-in general
    // agent, so it is not removed.
    editor.remove("build")
    editor.remove("plan")
    editor.remove("explore")

    // Hidden built-ins are visible to this editor, so the title model comes
    // from the mapping here rather than from a generated file.
    const title = editor.get("title")
    if (title) {
      title.steps = 1
      const ref = mapping["title"]
      const parsed = ref ? parseModelRef(ref) : null
      if (parsed) {
        title.model = {
          providerID: Provider.ID.make(parsed.providerID),
          id: Model.ID.make(parsed.id),
          ...(parsed.variant ? { variant: Model.VariantID.make(parsed.variant) } : {}),
        }
      }
    }

    editor.default("main")
  })

  const watcher = watchMapping(async (next) => {
    mapping = next
    await sync()
    await ctx.agent.reload()
  })

  await ctx.agent.reload()

  return async () => {
    watcher?.close()
    await removeStale(target, new Set())
    await ctx.agent.reload()
  }
}
